// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADwitZFaNW6ymNt2i1eoR0GfAJEHHsLJE',
    appId: '1:10670091685:web:497b40b4c5e2dc7b5c4c4c',
    messagingSenderId: '10670091685',
    projectId: 'plants-admin-panel',
    authDomain: 'plants-admin-panel.firebaseapp.com',
    storageBucket: 'plants-admin-panel.firebasestorage.app',
    measurementId: 'G-TY853SJWF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz72RNXdu2skmQx6PHE5C9UCDAgfqUDP8',
    appId: '1:10670091685:android:312ac5c3f09997515c4c4c',
    messagingSenderId: '10670091685',
    projectId: 'plants-admin-panel',
    storageBucket: 'plants-admin-panel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRSGhJZpYXzxajdBG-VD9mKf4G4zhAJbc',
    appId: '1:10670091685:ios:56fd4f89eb5133485c4c4c',
    messagingSenderId: '10670091685',
    projectId: 'plants-admin-panel',
    storageBucket: 'plants-admin-panel.firebasestorage.app',
    iosBundleId: 'com.example.robin11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRSGhJZpYXzxajdBG-VD9mKf4G4zhAJbc',
    appId: '1:10670091685:ios:56fd4f89eb5133485c4c4c',
    messagingSenderId: '10670091685',
    projectId: 'plants-admin-panel',
    storageBucket: 'plants-admin-panel.firebasestorage.app',
    iosBundleId: 'com.example.robin11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADwitZFaNW6ymNt2i1eoR0GfAJEHHsLJE',
    appId: '1:10670091685:web:3ff791a429bd44795c4c4c',
    messagingSenderId: '10670091685',
    projectId: 'plants-admin-panel',
    authDomain: 'plants-admin-panel.firebaseapp.com',
    storageBucket: 'plants-admin-panel.firebasestorage.app',
    measurementId: 'G-DJH3KP1V74',
  );
}
